### ISSUE TITLE
ValueError: Expected parameter concentration (Tensor of shape (64, 1)) of distribution Gamma(concentration: torch.Size([64, 1]), rate: torch.Size([64, 1])) to satisfy the constraint GreaterThan(lower_bound=0.0), but found invalid values:

### ISSUE THREAD

**Issue by kurvaraviteja355** [devmofl/M5_Accuracy_3rd#2]
Hello, Thank you for the Paper **Robust recurrent network model for intermittent time-series
forecasting**

I have tried to run  M5 dataset but i got the error which I cant understand. Could you please expain the why the error is occuring 

``python` m5/training.py --trial 't1' --data_path 'data/m5'

2023-03-17 09:37:30.462528: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-03-17 09:37:32.086063: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
2023-03-17 09:37:32.086207: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
2023-03-17 09:37:32.086228: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2023-03-17 09:37:35,160              mofl      INFO	Logging to logs/m5_submission/rolled_deepAR/drop1/t1/log.txt...
/gdrive/My Drive/M5_Accuracy_3rd-master/m5/load_dataset.py:192: FutureWarning: The 'freq' argument in Timestamp is deprecated and will be removed in a future version.
  start_date = pd.Timestamp("2011-01-29", freq='1D')
/gdrive/My Drive/M5_Accuracy_3rd-master/m5/pts/dataset/process.py:29: FutureWarning: The 'freq' argument in Timestamp is deprecated and will be removed in a future version.
  timestamp = pd.Timestamp(string, freq=freq)
/gdrive/My Drive/M5_Accuracy_3rd-master/m5/pts/dataset/process.py:32: FutureWarning: Timestamp.freq is deprecated and will be removed in a future version.
  if isinstance(timestamp.freq, Tick):
/gdrive/My Drive/M5_Accuracy_3rd-master/m5/pts/dataset/process.py:33: FutureWarning: Timestamp.freq is deprecated and will be removed in a future version.
  return pd.Timestamp(timestamp.floor(timestamp.freq), timestamp.freq)
/gdrive/My Drive/M5_Accuracy_3rd-master/m5/pts/dataset/process.py:33: FutureWarning: The 'freq' argument in Timestamp is deprecated and will be removed in a future version.
  return pd.Timestamp(timestamp.floor(timestamp.freq), timestamp.freq)
2023-03-17 09:38:16,984     mofl.training      INFO	Using rolled_deepAR model...
/usr/local/lib/python3.9/dist-packages/torch/utils/data/dataloader.py:561: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
2023-03-17 09:38:26,476      mofl.trainer      INFO	Number of parameters in RolledDeepARTrainingNetwork: 377009
0it [00:00, ?it/s]/gdrive/My Drive/M5_Accuracy_3rd-master/m5/pts/transform/split.py:33: FutureWarning: Timestamp.freq is deprecated and will be removed in a future version.
  return _shift_timestamp_helper(ts, ts.freq, offset)
/gdrive/My Drive/M5_Accuracy_3rd-master/m5/pts/transform/split.py:52: FutureWarning: Timestamp.freq is deprecated and will be removed in a future version.
  return ts + offset * ts.freq
/gdrive/My Drive/M5_Accuracy_3rd-master/m5/pts/transform/split.py:33: FutureWarning: Timestamp.freq is deprecated and will be removed in a future version.
  return _shift_timestamp_helper(ts, ts.freq, offset)
/gdrive/My Drive/M5_Accuracy_3rd-master/m5/pts/transform/split.py:52: FutureWarning: Timestamp.freq is deprecated and will be removed in a future version.
  return ts + offset * ts.freq
/gdrive/My Drive/M5_Accuracy_3rd-master/m5/pts/transform/split.py:33: FutureWarning: Timestamp.freq is deprecated and will be removed in a future version.
  return _shift_timestamp_helper(ts, ts.freq, offset)
/gdrive/My Drive/M5_Accuracy_3rd-master/m5/pts/transform/split.py:52: FutureWarning: Timestamp.freq is deprecated and will be removed in a future version.
  return ts + offset * ts.freq
/gdrive/My Drive/M5_Accuracy_3rd-master/m5/pts/transform/split.py:33: FutureWarning: Timestamp.freq is deprecated and will be removed in a future version.
  return _shift_timestamp_helper(ts, ts.freq, offset)
/gdrive/My Drive/M5_Accuracy_3rd-master/m5/pts/transform/split.py:52: FutureWarning: Timestamp.freq is deprecated and will be removed in a future version.
  return ts + offset * ts.freq
/gdrive/My Drive/M5_Accuracy_3rd-master/m5/pts/transform/feature.py:179: FutureWarning: Timestamp.freq is deprecated and will be removed in a future version.
  self._min_time_point, self._max_time_point, freq=start.freq
/gdrive/My Drive/M5_Accuracy_3rd-master/m5/pts/transform/feature.py:179: FutureWarning: Timestamp.freq is deprecated and will be removed in a future version.
  self._min_time_point, self._max_time_point, freq=start.freq
/gdrive/My Drive/M5_Accuracy_3rd-master/m5/pts/transform/feature.py:179: FutureWarning: Timestamp.freq is deprecated and will be removed in a future version.
  self._min_time_point, self._max_time_point, freq=start.freq
/gdrive/My Drive/M5_Accuracy_3rd-master/m5/pts/transform/feature.py:179: FutureWarning: Timestamp.freq is deprecated and will be removed in a future version.
  self._min_time_point, self._max_time_point, freq=start.freq
/gdrive/My Drive/M5_Accuracy_3rd-master/m5/pts/feature/time_feature.py:111: FutureWarning: weekofyear and week have been deprecated, please use DatetimeIndex.isocalendar().week instead, which returns a Series. To exactly reproduce the behavior of week and weekofyear and return an Index, you may call pd.Int64Index(idx.isocalendar().week)
  return (index.weekofyear -1) / 51.0 - 0.5 # weekofyear: 1~52
/gdrive/My Drive/M5_Accuracy_3rd-master/m5/pts/feature/time_feature.py:111: FutureWarning: weekofyear and week have been deprecated, please use DatetimeIndex.isocalendar().week instead, which returns a Series. To exactly reproduce the behavior of week and weekofyear and return an Index, you may call pd.Int64Index(idx.isocalendar().week)
  return (index.weekofyear -1) / 51.0 - 0.5 # weekofyear: 1~52
/gdrive/My Drive/M5_Accuracy_3rd-master/m5/pts/feature/time_feature.py:111: FutureWarning: weekofyear and week have been deprecated, please use DatetimeIndex.isocalendar().week instead, which returns a Series. To exactly reproduce the behavior of week and weekofyear and return an Index, you may call pd.Int64Index(idx.isocalendar().week)
  return (index.weekofyear -1) / 51.0 - 0.5 # weekofyear: 1~52
/gdrive/My Drive/M5_Accuracy_3rd-master/m5/pts/feature/time_feature.py:111: FutureWarning: weekofyear and week have been deprecated, please use DatetimeIndex.isocalendar().week instead, which returns a Series. To exactly reproduce the behavior of week and weekofyear and return an Index, you may call pd.Int64Index(idx.isocalendar().week)
  return (index.weekofyear -1) / 51.0 - 0.5 # weekofyear: 1~52
/gdrive/My Drive/M5_Accuracy_3rd-master/m5/pts/transform/split.py:33: FutureWarning: Timestamp.freq is deprecated and will be removed in a future version.
  return _shift_timestamp_helper(ts, ts.freq, offset)
/gdrive/My Drive/M5_Accuracy_3rd-master/m5/pts/transform/split.py:33: FutureWarning: Timestamp.freq is deprecated and will be removed in a future version.
  return _shift_timestamp_helper(ts, ts.freq, offset)
/gdrive/My Drive/M5_Accuracy_3rd-master/m5/pts/transform/split.py:52: FutureWarning: Timestamp.freq is deprecated and will be removed in a future version.
  return ts + offset * ts.freq
/gdrive/My Drive/M5_Accuracy_3rd-master/m5/pts/transform/split.py:52: FutureWarning: Timestamp.freq is deprecated and will be removed in a future version.
  return ts + offset * ts.freq
/gdrive/My Drive/M5_Accuracy_3rd-master/m5/pts/transform/split.py:33: FutureWarning: Timestamp.freq is deprecated and will be removed in a future version.
  return _shift_timestamp_helper(ts, ts.freq, offset)
/gdrive/My Drive/M5_Accuracy_3rd-master/m5/pts/transform/split.py:52: FutureWarning: Timestamp.freq is deprecated and will be removed in a future version.
  return ts + offset * ts.freq
/gdrive/My Drive/M5_Accuracy_3rd-master/m5/pts/transform/split.py:33: FutureWarning: Timestamp.freq is deprecated and will be removed in a future version.
  return _shift_timestamp_helper(ts, ts.freq, offset)
/gdrive/My Drive/M5_Accuracy_3rd-master/m5/pts/transform/split.py:52: FutureWarning: Timestamp.freq is deprecated and will be removed in a future version.
  return ts + offset * ts.freq
/gdrive/My Drive/M5_Accuracy_3rd-master/m5/pts/transform/feature.py:179: FutureWarning: Timestamp.freq is deprecated and will be removed in a future version.
  self._min_time_point, self._max_time_point, freq=start.freq
/gdrive/My Drive/M5_Accuracy_3rd-master/m5/pts/feature/time_feature.py:111: FutureWarning: weekofyear and week have been deprecated, please use DatetimeIndex.isocalendar().week instead, which returns a Series. To exactly reproduce the behavior of week and weekofyear and return an Index, you may call pd.Int64Index(idx.isocalendar().week)
  return (index.weekofyear -1) / 51.0 - 0.5 # weekofyear: 1~52
/gdrive/My Drive/M5_Accuracy_3rd-master/m5/pts/transform/feature.py:179: FutureWarning: Timestamp.freq is deprecated and will be removed in a future version.
  self._min_time_point, self._max_time_point, freq=start.freq
/gdrive/My Drive/M5_Accuracy_3rd-master/m5/pts/feature/time_feature.py:111: FutureWarning: weekofyear and week have been deprecated, please use DatetimeIndex.isocalendar().week instead, which returns a Series. To exactly reproduce the behavior of week and weekofyear and return an Index, you may call pd.Int64Index(idx.isocalendar().week)
  return (index.weekofyear -1) / 51.0 - 0.5 # weekofyear: 1~52
/gdrive/My Drive/M5_Accuracy_3rd-master/m5/pts/transform/feature.py:179: FutureWarning: Timestamp.freq is deprecated and will be removed in a future version.
  self._min_time_point, self._max_time_point, freq=start.freq
/gdrive/My Drive/M5_Accuracy_3rd-master/m5/pts/feature/time_feature.py:111: FutureWarning: weekofyear and week have been deprecated, please use DatetimeIndex.isocalendar().week instead, which returns a Series. To exactly reproduce the behavior of week and weekofyear and return an Index, you may call pd.Int64Index(idx.isocalendar().week)
  return (index.weekofyear -1) / 51.0 - 0.5 # weekofyear: 1~52
/gdrive/My Drive/M5_Accuracy_3rd-master/m5/pts/transform/split.py:33: FutureWarning: Timestamp.freq is deprecated and will be removed in a future version.
  return _shift_timestamp_helper(ts, ts.freq, offset)
/gdrive/My Drive/M5_Accuracy_3rd-master/m5/pts/transform/split.py:52: FutureWarning: Timestamp.freq is deprecated and will be removed in a future version.
  return ts + offset * ts.freq
/gdrive/My Drive/M5_Accuracy_3rd-master/m5/pts/transform/split.py:33: FutureWarning: Timestamp.freq is deprecated and will be removed in a future version.
  return _shift_timestamp_helper(ts, ts.freq, offset)
/gdrive/My Drive/M5_Accuracy_3rd-master/m5/pts/transform/split.py:52: FutureWarning: Timestamp.freq is deprecated and will be removed in a future version.
  return ts + offset * ts.freq
/gdrive/My Drive/M5_Accuracy_3rd-master/m5/pts/transform/split.py:33: FutureWarning: Timestamp.freq is deprecated and will be removed in a future version.
  return _shift_timestamp_helper(ts, ts.freq, offset)
/gdrive/My Drive/M5_Accuracy_3rd-master/m5/pts/transform/split.py:52: FutureWarning: Timestamp.freq is deprecated and will be removed in a future version.
  return ts + offset * ts.freq
/gdrive/My Drive/M5_Accuracy_3rd-master/m5/pts/transform/feature.py:179: FutureWarning: Timestamp.freq is deprecated and will be removed in a future version.
  self._min_time_point, self._max_time_point, freq=start.freq
/gdrive/My Drive/M5_Accuracy_3rd-master/m5/pts/feature/time_feature.py:111: FutureWarning: weekofyear and week have been deprecated, please use DatetimeIndex.isocalendar().week instead, which returns a Series. To exactly reproduce the behavior of week and weekofyear and return an Index, you may call pd.Int64Index(idx.isocalendar().week)
  return (index.weekofyear -1) / 51.0 - 0.5 # weekofyear: 1~52
/gdrive/My Drive/M5_Accuracy_3rd-master/m5/pts/transform/split.py:33: FutureWarning: Timestamp.freq is deprecated and will be removed in a future version.
  return _shift_timestamp_helper(ts, ts.freq, offset)
/gdrive/My Drive/M5_Accuracy_3rd-master/m5/pts/transform/split.py:52: FutureWarning: Timestamp.freq is deprecated and will be removed in a future version.
  return ts + offset * ts.freq
/usr/local/lib/python3.9/dist-packages/torch/distributions/distribution.py:51: UserWarning: <class 'pts.modules.distribution.tweedie.Tweedie'> does not define `arg_constraints`. Please set `arg_constraints = {}` or initialize the distribution with `validate_args=False` to turn off validation.
  warnings.warn(f'{self.__class__} does not define `arg_constraints`. ' +
0it [00:02, ?it/s]
Traceback (most recent call last):
  File "/gdrive/My Drive/M5_Accuracy_3rd-master/m5/training.py", line 125, in <module>
    main(args)
  File "/gdrive/My Drive/M5_Accuracy_3rd-master/m5/training.py", line 94, in main
    predictor = estimator.train(train_ds, validation_period=10)
  File "/gdrive/My Drive/M5_Accuracy_3rd-master/m5/pts/model/estimator.py", line 165, in train
    return self.train_model(training_data, validation_period).predictor
  File "/gdrive/My Drive/M5_Accuracy_3rd-master/m5/pts/model/estimator.py", line 147, in train_model
    self.trainer(
  File "/gdrive/My Drive/M5_Accuracy_3rd-master/m5/pts/trainer.py", line 173, in __call__
    epoch_loss = loop(epoch_no, training_data_loader)
  File "/gdrive/My Drive/M5_Accuracy_3rd-master/m5/pts/trainer.py", line 98, in loop
    output = net(*inputs)
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/gdrive/My Drive/M5_Accuracy_3rd-master/m5/pts/model/deepar/deepar_network.py", line 407, in forward
    new_samples = distr.sample()
  File "/gdrive/My Drive/M5_Accuracy_3rd-master/m5/pts/modules/distribution/tweedie.py", line 53, in sample
    gamma = torch.distributions.gamma.Gamma(N*alpha, beta)
  File "/usr/local/lib/python3.9/dist-packages/torch/distributions/gamma.py", line 54, in __init__
    super().__init__(batch_shape, validate_args=validate_args)
  File "/usr/local/lib/python3.9/dist-packages/torch/distributions/distribution.py", line 62, in __init__
    raise ValueError(
ValueError: Expected parameter concentration (Tensor of shape (64, 1)) of distribution Gamma(concentration: torch.Size([64, 1]), rate: torch.Size([64, 1])) to satisfy the constraint GreaterThan(lower_bound=0.0), but found invalid values:
tensor([[ 0.0000],
        [ 4.0000],
        [ 0.0000],
        [ 4.0000],
        [ 4.0000],
        [12.0000],
        [ 4.0000],
        [ 0.0000],
        [ 8.0000],
        [ 4.0000],
        [ 8.0000],
        [ 4.0000],
        [ 4.0000],
        [ 0.0000],
        [ 8.0000],
        [ 8.0000],
        [12.0000],
        [ 4.0000],
        [ 8.0000],
        [ 0.0000],
        [ 8.0000],
        [ 0.0000],
        [ 4.0000],
        [ 4.0000],
        [ 0.0000],
        [ 8.0000],
        [12.0000],
        [ 8.0000],
        [ 0.0000],
        [ 4.0000],
        [ 0.0000],
        [ 8.0000],
        [ 8.0000],
        [ 4.0000],
        [12.0000],
        [ 4.0000],
        [ 4.0000],
        [ 0.0000],
        [ 8.0000],
        [ 8.0000],
        [ 0.0000],
        [ 4.0000],
        [ 0.0000],
        [ 8.0000],
        [ 8.0000],
        [ 0.0000],
        [ 8.0000],
        [ 8.0000],
        [ 8.0000],
        [ 4.0000],
        [ 4.0000],
        [ 8.0000],
        [12.0000],
        [12.0000],
        [ 8.0000],
        [ 0.0000],
        [ 8.0000],
        [ 4.0000],
        [12.0000],
        [12.0000],
        [ 4.0000],
        [ 0.0000],
        [ 8.0000],
        [ 8.0000]], device='cuda:0', `grad_fn=<MulBackward0>)``

**Comment by kurvaraviteja355** [comment]
Sorry my bad, I used different version of torch before
